--- 
javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - application
- lightview:
  - scriptaculous    
  - lightview
- map:  
  - ym4r-gm
  - wms-gs
- optional:  
  - markerGroup
  - geoRssOverlay 
   
stylesheets: 
- base:
  - reset
  - application_base 
  - application
- hermes:
  - reset
  - hermes_base
  - hermes
- hermes_ie:
  - reset
  - hermes_base
  - hermes
  - hermes_ie
- hermes_white:
  - reset
  - hermes_white_base
  - hermes_white  
- lightview:  
  - lightview
